# Generated by Django 6.0 on 2025-12-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beta", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PingCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ping Counter",
                "verbose_name_plural": "Ping Counters",
            },
        ),
    ]
