services:
  beta-app:
    image: localhost/dagobert:local
    container_name: beta
    restart: 'never'
    volumes:
      - local_data:/data/market_analysis
    ports:
      - "28001:8001"
    networks:
      - default_net
    environment:
      MYSQL_ENGINE: ${MYSQL_ENGINE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mariadb
      MYSQL_PORT: '3306'
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy

  cron-app:
    container_name: crontainer
    image: localhost/crontainer:local
    networks:
      - default_net
    depends_on:
      - beta-app

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    volumes:
      - local_mysql:/var/lib/mysql:Z
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
     - .env
    ports:
      - "23306:3306"
    networks:
      - default_net
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      #start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=1000
        
volumes:
  local_mysql:
  local_data:

networks:
  default_net:
    driver: bridge