services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    volumes:
      - local_mysql:/var/lib/mysql:Z
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
     - .env
    ports:
      - "23306:3306"
    networks:
      - default_net
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
     - .env
    ports:
      - "28080:80"
    networks:
      - default_net
    depends_on:
      - mariadb  
      
volumes:
  local_mysql:

networks:
  default_net:
    driver: bridge